### ISSUE TITLE
SourceSetContainer error while using coverallsJacoco

### ISSUE THREAD

**Issue by lenoirzamboni** [nbaztec/coveralls-jacoco-gradle-plugin#9] opened 2020-08-21 19:10 UTC
Hello. I am trying yo use `coveralls-jacoco-gradle-plugin` on my project, but when I run the command `./gradlew coverallsJacoco` I keep receiving this error:

```js
Task :coverallsJacoco FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':coverallsJacoco'.
> Extension of type 'SourceSetContainer' does not exist. Currently registered extension types: [ExtraPropertiesExtension, CoverallsJacocoPluginExtension, Boolean]

```

My project is not Kotlin and I have a separate gradle file to setup the jacoco settings: (code-coverage.gradle)

```js
apply plugin: 'jacoco-android'

jacoco {
    toolVersion = "0.8.4"
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
}

jacocoAndroidUnitTestReport {
    csv.enabled false
    html.enabled false
    xml.enabled true
}

jacocoAndroidUnitTestReport {
    excludes += ['**/R.class',
                 '**/R$*.class',
                 '**/BuildConfig.*',
                 '**/Manifest*.*',
                 '**/*Test*.*',
                 '**/*_ViewBinding.*',
                 '**/*Dagger*Component*.*',
                 '**/*MembersInjector.*',
                 '**/*_*Factory.*',
                 '**/*RealmProxy.*',
                 '**/DefaultRealmModuleMediator.*',
                 '**/DefaultRealmModule.*',
                 '**/*RealmProxy*ColumnInfo.*',
                 'android/**/*.*']
}

coverallsJacoco {
    reportPath = "$buildDir/reports/jacoco/test/jacocoTestReport.xml"
}
```

For jacoco, I am using this gradle plugin:
[com.dicedmelon.gradle:jacoco-android](https://github.com/arturdm/jacoco-android-gradle-plugin), version 0.1.4.

**Comment by nbaztec** [comment] 2020-08-25 05:05
Thanks for reporting, I will take a look. Would you happen to have a sample project available?

**Comment by lenoirzamboni** [comment] 2020-08-26 14:32
@nbaztec Thanks. Right now, I don't have a public sample project that I can share with you, sorry.

**Comment by nbaztec** [comment] 2020-08-26 16:38
I tried setting up a basic project with that plugin, but unfortunately cannot replicate the issue. Could you let me know the Gradle version and the plugin version, please and any other plugins in use and the type of project/language? Maybe I'll have some luck then.

Let me know if you get some time to set up a dummy project, would be greatly helpful in identifying the issue.

**Comment by lenoirzamboni** [comment] 2020-08-28 12:29
Hi!

Project: Android with Java
Jacoco: I'm using the [jacoco-android-gradle-plugin, v. 0.1.4](https://github.com/arturdm/jacoco-android-gradle-plugin), along with jacoco tools version 0.8.4.
Gradle version: 5.6.4

And that's it, nothing more.

**Comment by nbaztec** [comment] 2020-09-06 14:22
Could you please take a look with a more recent `1.2.2` version, if the issue is resolved?

**Comment by mattbusuu** [comment] 2020-09-11 15:29
I'm getting the same issue also on 1.2.2

**Comment by nbaztec** [comment] 2020-09-14 05:53
@mattbusuu a sample project would really help in identifying the issue, if it can be reproduced. Would that be possible? Thanks.

**Comment by mattbusuu** [comment] 2020-09-30 15:54
Fixed on 1.2.3 for me.

**Comment by nbaztec** [comment] 2020-10-02 08:08
@lenoirzamboni could you verify it as well please?

**Comment by lenoirzamboni** [comment] 2020-10-02 12:57
@nbaztec We had to use another library because of time constraints. 

But thanks for fixing this! If you want to, feel free to close this issue.

**Closed** 2020-10-02 14:05 UTC

**Comment by gongracr** [comment] 2020-11-11 16:45
I am facing currently the same issue. Atm I have an Android Kotlin project fed by multiple flavoured modules also written in Kotlin. All these modules have different unit tests sets whose coverage reports I need to combine into a unified central report and upload to coveralls. For this purpose I used another well known plugin `com.vanniktech.android.junit.jacoco` that stores the final merged report on `$buildDir/reports/jacoco/jacoco.xml`. 

However when I try to run your plugin to upload this central report to coveralls, the compiler will fail with the exact error trace above, no matter what kind of path I provide for `reportSourceSets` . 
Do you know how would it be possible to specify correctly the path to these source sets? Also note I am using running gradle version `6.1.1`

Here is a link to a dummy project I just created to recreate the given context 
https://github.com/gongracr/DummyJacocoCoveralls

**Comment by nbaztec** [comment] 2020-11-11 18:32
Thanks for providing the sample project. Personally I'm using the default `jacoco` plugin and using the following to run & gather coverage data.

I would recommend the following update to your `build.gradle` here:

```groovy
// ignore any subproject, if required `subprojects.findAll{ it.name != 'customSubProject' }`
def coveredProjects = subprojects

// configure() method takes a list as an argument and applies the configuration to the projects in this list.
configure(coveredProjects) { p ->
    p.evaluate()

    // Here we apply jacoco plugin to every project
    apply plugin: 'jacoco'
    // Set Jacoco version
    jacoco {
        toolVersion = "0.8.5"
    }

    // Here we create the task to generate Jacoco report
    // It depends to unit test task we don't have to manually running unit test before the task
    task jacocoReport(type: JacocoReport, dependsOn: 'test') {

        // Define what type of report we should generate
        // If we don't want to process the data further, html should be enough
        reports {
            xml.enabled = true
            html.enabled = true
        }

        // Setup the .class, source, and execution directories
        final fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', 'android/**/*.*']

        sourceDirectories.setFrom files(["${p.projectDir}/src/main/java"])
        classDirectories.setFrom files([fileTree(dir: "${p.buildDir}/classes", excludes: fileFilter)])
        executionData.setFrom fileTree(dir: p.buildDir, includes: [
                'jacoco/*.exec', 'outputs/code-coverage/connected/*coverage.ec'
        ])
    }
}

apply plugin: 'jacoco'
apply plugin: 'com.github.nbaztec.coveralls-jacoco'

task jacocoFullReport(type: JacocoReport, group: 'Coverage reports') {
    def projects = coveredProjects

    // Here we depend on the jacocoReport task that we created before
    dependsOn(projects.jacocoReport)

    final source = files(projects.jacocoReport.sourceDirectories)

    additionalSourceDirs.setFrom source
    sourceDirectories.setFrom source

    classDirectories.setFrom files(projects.jacocoReport.classDirectories)
    executionData.setFrom files(projects.jacocoReport.executionData)

    reports {
        html {
            enabled true
            destination file("$buildDir/reports/jacoco/html")
        }
        xml {
            enabled true
            destination file("$buildDir/reports/jacoco/jacocoFullReport.xml")
        }
    }

    doFirst {
        executionData.setFrom files(executionData.findAll { it.exists() })
    }

    coverallsJacoco {
        reportPath = "$buildDir/reports/jacoco/jacocoFullReport.xml"
        reportSourceSets =  projects.jacocoReport.sourceDirectories.collect{ it.getFiles() }.flatten()
    }
}
```

`$ COVERALLS_REPO_TOKEN=foo ./gradlew jacocoFullReport coverallsJacoco` should work then.

**Comment by gongracr** [comment] 2020-11-13 15:48
Woow thanks a lot for your detailed answer 👏 ! 
However I couldn't manage to make it work on my real project yet. I think it might be related on how Gradle crawls those projects/libraries and match correctly their code with their corresponding jacoco `*.exec` file. Even though these files seem to be created and placed well inside the lib package, apparently Jacoco can't map them with their Kotlin counterpart right after, failing to build any proper final full report.

In my real project, the internal libraries I use are declared as android libraries, and not as Java libraries. I forgot to add that to the original dummy project I posted previously. After making those updates to this Dummy Project, now it doesn't create the final report as it did before, and unfortunately I can't figure out what is missing as Gradle logs are not really showing any clear errors...
It would be awesome if you could run the latest state of the [Dummy Project](https://github.com/gongracr/DummyJacocoCoveralls) again and let me know if you find something odd.

**Comment by nbaztec** [comment] 2020-11-15 12:34
@gongracr you were correct about the Android generated output being elsewhere. I've updated the [docs](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin#multi-project-support---android) accordingly

lines need to be added [here](https://github.com/gongracr/DummyJacocoCoveralls/blob/main/build.gradle#L53):

```groovy
        ....
        classDirectories.setFrom files([
            fileTree(dir: "${p.buildDir}/classes", excludes: fileFilter),
            fileTree(dir: "${p.buildDir}/intermediates/javac/debug", excludes: fileFilter),
            fileTree(dir: "${p.buildDir}/tmp/kotlin-classes/debug", excludes: fileFilter),
        ])
        ....
```

and a bugfix to ensure the reporting is done _before_ coverage in case the tasks are run in single line, [here](https://github.com/gongracr/DummyJacocoCoveralls/blob/main/build.gradle#L95) :


```groovy
    ....
    coverallsJacoco {
        reportPath = "$buildDir/reports/jacoco/jacocoFullReport.xml"
        reportSourceSets =  projects.jacocoReport.sourceDirectories.collect{ it.getFiles() }.flatten()
    }

    tasks.coverallsJacoco.dependsOn(it)
    ....
```
If there are further issues, could you please create a separate issue, so we don't hijack this one? :)
Thanks

**Comment by gongracr** [comment] 2020-11-16 15:42
Now it worked like a charm, thanks a lot 🏆 !!

Small note: I also needed to add the following code [in this line here](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/blame/main/README.md#L212), otherwise the report will not include Unit Tests performed using Roboelectric, in case you wanted to update that to your docs too.
```Groovy
    tasks.withType(Test) {
        jacoco.includeNoLocationClasses = true
    }
```
